### ISSUE TITLE
How can I reproduce the experiment (fig.10) in the paper?

### ISSUE THREAD

**Issue by h2wonS** [acsl-technion/znswap#4]
Hi, @shaiberg1 
I want to reproduce your experiment (fig10 and fig1) in ZNSwap paper.

First I ran this scipts to swap on the ZNS SSD (WD ZN540 8TB), and I set the number of swap-zone to 50, because my RAM size is 50GB.
`#!/bin/bash                                                 
                                                            
sudo swapoff /dev/nvme1n1                                   
                                                            
sudo nvme zns reset-zone -a /dev/nvme1n1                    
                                                            
echo 50 | sudo tee  /sys/kernel/mm/zns_swap/nr_swap_zones   
                                                            
echo 1 | sudo tee /sys/kernel/mm/zns_swap/zns_policy        
                                                            
echo 1 | sudo tee /sys/kernel/mm/zns_swap/zns_cgroup_account
                                                            
sudo mkswap /dev/nvme1n1                                    
                                                            
sudo swapon /dev/nvme1n1                                    
                                                            
sudo mkdir /sys/fs/cgroup/vm                                
sudo mkdir /sys/fs/cgroup/vm/tasks                          `

Then, I ran the 'vm-scalability/case-anon-w-rand-mt' with this modification
`#!/bin/sh                                                    
                                                             
read pid                                                     
echo ${pid} > /sys/fs/cgroup/vm/tasks/cgroup.procs           
echo $((2* 1024* 1024* 1024)) > /sys/fs/cgroup/vm/memory.high
                                                             
. ./hw_vars                                                  
                                                             
[ -n "$unit_size" ] || unit_size=$((mem / 2))                
$USEMEM -t $((16)) --random $((unit_size / 16))              `

It means that the number of available cores in my setting is 16,
and the process{pid}'s memory is limited 2GB by cgroup

After that, I monitored the memory and swap-device stat with "htop" & "dstat"

I could see the swap runs well until the total amount of data is about 22~23GB.
But the kernel suddenly stopped when the experiment is almost done.
(In this case, the unit_size of the experiment is 22-24GB, because the case-anon-w-rand-mt workload runs unit_size which is limited by memorysize / 2)

For these issues, I was wondering how you record the throughput like fig1 and fig10.

Also, I was wondering how I can change the device utilization.

Please let me know,

Thanks :)

**Comment by shaiberg1** [comment]
Hi @h2wonS!

I'll first address your general questions and some other pointers, and then we'll dive into the technical stuff.

First, since you've set your number of swap zones == 50, this means that the overall amount of capacity available for the entire device is 50GB (this includes over-provisioning). This essentially emulates an SSD with 50GB total overall capacity. If you wish to recreate figures {1,10}, you need to take into account the OP which the regular (non-ZNS) SSD has, and apply it to the ZNS drive. This means that if your original SSD has 50GB capacity, and has (for example) 17%OP, you'd need to allocate 1.17*50 zones. You need the ability to configure the OP non-ZNS SSD to achieve such low OP for the specific capacity, since usually the OP is specified as a large number of blocks.

Also, please make sure that when you measure statistics, both SSDs are in "steady-state" from a WA and GC point of view, as per SNIA best practices (https://www.snia.org/sites/default/files/technical_work/PTS/SSS_PTS_2.0.2.pdf) - which essentially means to leave the machine running the workload for long enough to achieve stable results (which makes sure you write to all media 2x or so, and then measure the performance).

The device utilization basically means how much of the device you are using for swap out of the entire available swap device. So, if usemem utilizes 12 GB of memory, and you have a cgroup with 2GB RAM limit, you are essentially using ~10GB of swap. This means that with a 50GB ZNS swap size (excluding the OP), your utilization at this point is 20%.

Finally, to measure the WA on a traditional SSD, you'd need access to the internal SSD counters.

Now for the fun stuff (SJF):

1. The swap bandwidth is measured after achieving steady state, and you can use the "pswp{in,out}" counters in /proc/vmstat before and after the measurement period.
2. Since you are not using cgroup isolation (which is not needed for the figures), you can skip "echo 1 | sudo tee /sys/kernel/mm/zns_swap/zns_cgroup_account"
3. To help debug the situation, I'd like to receive the following info if that's ok:
- How much memory did you configure usemem to use when the kernel hangs?
- Could you try a smaller amount of memory (i.e., 10GiB) just to see that it runs to completion? (also, please run it for a long time so that znGC will kick in).
- When the kernel hangs, does it print anything in dmesg? (maybe it does over the IPMI KVM / SOL?)

If you have any further questions please don't hesitate to ask :)

Thanks!

**Comment by shaiberg1** [comment]
Another question - did you format the ZNS device with the correct lbaf (64B metadata support)?

Thanks

**Comment by h2wonS** [comment]
First of all, Thanks for your kind answer! @shaiberg1 
It really helps me to understand the experiment.

Yeah, I formatted the ZNS device with the lbaf(supporting 64B metadata).

In my setting, the usemem is configured with the 25GB(ex. physical memsize/2). 
(Did you mean that the "unit_size" of the case-anon-w-rand-mt code? I modified this variable to debug this issue)

Although I tried with the smaller amount of usemem (i.e.. unit_size= 10GB, 20GB),
the kernel hang again and again when the total amount of memory & swap space almost reaches the usemem size.
For example, when I set the usemem size (unit_size) to 20GB and I set the memory limit to 2GB with cgroup, the kernel hang when the total amount of memory(2GB) and swapspace(18GB) reaches the usemem size(20GB).

Also, there's no message in dmesg... :(

Thanks!

**Comment by h2wonS** [comment]
Oh I have another question,, Which policy do I need to take for reproducing the figure1&figure10?

It seems that the default policy is no.3 (per VMA), because I didn't change the policy since I've built the kernel.

Also, I think the ZNGC is triggered when the empty state zone is less than pre-defined threshold, the "low_wmark"... (am I right?)
So I want to run for a long time to start znGC as you recommended, but I don't know how to do exactly...

Thanks

**Comment by shaiberg1** [comment]
Hi @h2wonS!

From what I can gather from the experiment, I think that the second the system wants to swap-in data for the random reads, the kernel crashes. Lets make sure that this is the case by just ruling out some things :)

Lets run again the same workload, but:
- configure the number of swap zones to 512
- run unit_size 20GB
- keep a window with ```watch -n 0.2 cat /proc/vmstat ``` open, and keep an eye out for "pswpin", to see if that value increases beyond 0.

If the kernel crashes and the pswpin value remains 0, I assume there is a problem with the swap-in path. If it continues to run and crashes later on it might be znGC (which has its own counter in vmstat to keep an eye on!).

Are you by any chance running this on a QEMU VM with a vfio-pci passthrough for the SSD? If so, it would be really helpful in just seeing where the kernel has crashed in the code itself. If you need assistance in setting up a VM with ZNSwap and want to debug the code, I will be happy to help!

Hopefully we can get this issue resolved soon, and may even have the first pull request for the repo :)
Thanks

P.S the policy there is per-core policy
P.P.S yap, when the number of empty zones go under low_watermark, znGC is triggered. After you configure the swap device, you can see the value given to the low_watermark in the sysfs files

**Comment by h2wonS** [comment]
Hello @shaiberg1 !

Your explanation has been incredibly helpful.

I increased the number of swap zones to 512 and set the unit size to 20GB. I monitored it with the command "watch -n 0.2 cat /proc/vmstat" and observed that the kernel didn't crash and the pswpin increased.
The memory usage remained at 2GB while the swap increased to 18GB. However, the benchmark (case-anon-w-rand-mt) did not finish after an hour, so I'm not sure if this is a problem.

Even though increasing the number of swap zones solved the issue, I still have some questions. 

First , I wonder if it's fine to set the swap zone to 512, though the size of  memory is almost 50GB. Is it okay to set the swap zone to 512 even if the memory size is quite less than 512GB? 

Additionally, do I need to set the values for low_wmark and high_wmark? 
It seems that default value for these is 0, but I think I should increase the low_wmark to trigger the znGC earlier or more frequently. Can you recommend a suitable value for me?

Thank you so much

**Comment by shaiberg1** [comment]
Hi @h2wonS!

So sorry for the late reply.

Lets make sure that znGC works as expected on your machine :) Please run the workload for a relatively long time (with the same number of zones), and keep an eye on the "pgznsgcwrite" in vmstat to see that znGC kicks in.

The default value of low_wmark and high_wmark are a function of the number of zones that have been provisioned for swap. It is entirely likely that with only 50 zones the watermarks are 0, which explains the kernel hanging!

If you want to recreate just figure 1 or 10, the local memory size does not really matter since you are running your workload in a memory-restricted cgroup (of 2GiB).

Please run the above and let me know if there are any issues :)
Thanks

**Comment by h2wonS** [comment]
Hi @shaiberg1 !

Finally, it works!
I could see znGC running as the number of "pgzns_gcwrite" increased.

It is assumed that the benchmarking was not working properly due to an external hacking attempt on my server machine.
Thanks to your describtion, I was able to complete the experiment.

With best regards,
thank you

**Comment by shaiberg1** [comment]
Hi @h2wonS !

I'm glad it works! And I hope the external hacking attempt has been properly taken care of :)

Please make sure that the watermark is at its default value when trying to recreate the figures in the paper (as large watermark values will trigger GC all the time unnecessarily).

If you have any further questions you are welcome to drop me an email (my address is shai [at] shai.pub).

Thanks!
